Updated etc/init.d/iptables to be ipv4 specific and made it systemd compliant

diff --git a/etc/init.d/iptables b/etc/init.d/iptables
--- a/etc/init.d/iptables
+++ b/etc/init.d/iptables
@@ -1,4 +1,18 @@
 #!/bin/bash
+# Author: David Latham <kiwilathams@gmail.com>
+# License: GPL v.2
+#
+### BEGIN INIT INFO
+# Provides:		iptables
+# Default-Start:	3 4 5
+# Default-Stop:		0 1 2 6
+# Short-Description:	Traditional Itables Implimentation (IPv4)
+# Long-Description:	Replacement for SuSEFirewall2 daemon that provides
+#	for the traditional configuration of iptables (IPv4) via
+#	/etc/sysconfig/iptables
+### END INIT INFO
+
+
 IPT=/usr/sbin/iptables
 IPTsave=/usr/sbin/iptables-save
 IPTrestore=/usr/sbin/iptables-restore
@@ -28,35 +42,45 @@ if [ -z $action ]; then
 	exit 1
 fi
 
-# Stop the system firewall Always
-systemctl stop SuSEfirewall2.service
+
+# Shell functions sourced from /etc/rc.status:
+#      rc_check         check and set local and overall rc status
+#      rc_status        check and set local and overall rc status
+#      rc_status -v     ditto but be verbose in local rc status
+#      rc_status -v -r  ditto and clear the local rc status
+#      rc_failed        set local and overall rc status to failed
+#      rc_failed <num>  set local and overall rc status to <num><num>
+#      rc_reset         clear local rc status (overall remains)
+#      rc_exit          exit appropriate to overall rc status
+. /etc/rc.status
 
 case $action in
 	"start")
-		echo "Starting iptables ...."
+		echo -n "Stopping SuSEfirewall2..."
+		rc_status -v
+		systemctl stop SuSEfirewall2
+		echo -n "Starting iptables..."
 		$IPTrestore < $IPTConfigSave
-		#$IP6restore < $IPTConfigSave
+		rc_status -v
+		echo -n "enabling ipv4.ip_forward"
+		sysctl net.ipv4.ip_forward=1
+		rc_status -v
 		;;
 	"stop")
-		echo "Stopping iptables ..."
+		echo -n "Stopping iptables ..."
 		$IPTrestore < $IPTConfigOpen
-		#$IP6restore < $IPTConfigOpen
+		rc_status -v
 		;;
 	"restart")
-		echo "Restarting iptables ..."
-                $IPTrestore < $IPTConfigOpen
-                #$IP6restore < $IPTConfigOpen
-                $IPTrestore < $IPTConfigSave
-                #$IP6restore < $IPTConfigSave
+		$0 stop
+		$0 start
 		;;
 	"status")
+		echo -n "Checking for iptables..."
 		$IPTsave
+		rc_status -v
 		;;
+	*)
+		usage
+		exit 1
 esac
-
-# turn on ip_forward
-sysctl net.ipv4.ip_forward=1
-
-# turn on dnsmasq
-systemctl start dnsmasq
-
